branch-defaults:
  default:
    environment: null
  master:
    environment: amrtrack-dev-env
global:
  application_name: amrtrack-demo
  branch: null
  default_ec2_keyname: AWS EC2
  default_platform: Python 3.6 running on 64bit Amazon Linux
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
